name: 'ServiceNow CI/CD Publish App'
description: 'Publishes the specified application to the application repository.'
author: "ServiceNow"
inputs:
  version:
    description: "Application version to publish"
    required: false
  devNotes:
    description: "Developer notes to store with the application."
    required: false
  versionTemplate:
    description: "Version template ( like 2.4 )."
    required: false
  versionFormat:
    description: "exact, detect, autodetect, template"
    required: false
outputs:
  rollbackVersion:
    description: "Rollback version"
  newVersion:
    description: "Incremented version"
runs:
  using: 'node12'
  main: './lib/index.js'
branding:
  icon: 'refresh-ccw'
  color: 'green'
